### ISSUE TITLE
Ajouter un id pour le menu Recherche (amélioration)

### ISSUE THREAD

**Issue by ghost** [Pluxopolis/plxMySearch#5]
Il serait intéressant d'ajouter un id pour le lien du menu Recherche. 
J'utilise  [Ajouter une icône aux menus des pages statiques ](http://pluxopolis.net/article48/ajouter-une-icone-aux-menus-des-pages-statiques) et sans modification dans le plugin, cela ne semble pas possible.

Il faudrait simplement modifier pour ajouter `id=\"search\"` à la ligne 98 de  plxMySearch/plxMySearch.php

```
echo "<?php array_splice(\$menus, ".($this->getParam('mnuPos')-1).", 0, '<li id=\"search\"><a class=\"static '.\$class.'\" href=\"'.\$this->plxMotor->urlRewrite('?".$this->getParam('url')."').'\" title=\"".$this->getParam('mnuName_'.$this->default_lang)."\">".$this->getParam('mnuName_'.$this->default_lang)."</a></li>'); ?>";      
```

**Comment by Pluxopolis** [comment]
implémenté
